"""added columns to feed table

Revision ID: 770063fc0a0d
Revises: 
Create Date: 2018-11-02 21:42:22.752123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770063fc0a0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archives', sa.Column('num_words', sa.Integer(), nullable=True))
    op.add_column('archives', sa.Column('sentence_breakdown', sa.JSON(), nullable=True))
    op.add_column('archives', sa.Column('vocab_score', sa.Integer(), nullable=True))
    op.drop_constraint('uq_archives_title', 'archives', type_='unique')
    op.add_column('feed', sa.Column('num_words', sa.Integer(), nullable=True))
    op.add_column('feed', sa.Column('sentence_breakdown', sa.JSON(), nullable=True))
    op.add_column('feed', sa.Column('vocab_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'vocab_score')
    op.drop_column('feed', 'sentence_breakdown')
    op.drop_column('feed', 'num_words')
    op.create_unique_constraint('uq_archives_title', 'archives', ['title'])
    op.drop_column('archives', 'vocab_score')
    op.drop_column('archives', 'sentence_breakdown')
    op.drop_column('archives', 'num_words')
    # ### end Alembic commands ###
